python .\trade_bot_fut_cuda.py .\data\RTY=F.csv rty_fut train
python .\trade_bot_fut_cuda.py .\data\RTY=F.csv rty_fut test

python .\trade_bot_fut_cuda.py .\data\CL=F.csv cl_fut train
python .\trade_bot_fut_cuda.py .\data\CL=F.csv cl_fut test

python .\trade_bot_fut_cuda.py .\data\LE=F.csv le_fut train
python .\trade_bot_fut_cuda.py .\data\LE=F.csv le_fut test

python .\trade_bot_fut_cuda.py .\data\GC=F.csv gc_fut train
python .\trade_bot_fut_cuda.py .\data\GC=F.csv gc_fut test

python .\trade_bot_fut_cuda.py .\data\ZN=F.csv zn_fut train
python .\trade_bot_fut_cuda.py .\data\ZN=F.csv zn_fut test

python .\trade_bot_fut_cuda.py .\data\6E=F.csv 6e_fut train
python .\trade_bot_fut_cuda.py .\data\6E=F.csv 6e_fut test