python .\trade_bot_lstm5_cuda.py .\data\RTY=F.csv rty_lstm5 train
python .\trade_bot_lstm5_cuda.py .\data\RTY=F.csv rty_lstm5 test

python .\trade_bot_lstm5_cuda.py .\data\CL=F.csv cl_lstm5 train
python .\trade_bot_lstm5_cuda.py .\data\CL=F.csv cl_lstm5 test

python .\trade_bot_lstm5_cuda.py .\data\LE=F.csv le_lstm5 train
python .\trade_bot_lstm5_cuda.py .\data\LE=F.csv le_lstm5 test

python .\trade_bot_lstm5_cuda.py .\data\GC=F.csv gc_lstm5 train
python .\trade_bot_lstm5_cuda.py .\data\GC=F.csv gc_lstm5 test

python .\trade_bot_lstm5_cuda.py .\data\ZN=F.csv zn_lstm5 train
python .\trade_bot_lstm5_cuda.py .\data\ZN=F.csv zn_lstm5 test

python .\trade_bot_lstm5_cuda.py .\data\6E=F.csv 6e_lstm5 train
python .\trade_bot_lstm5_cuda.py .\data\6E=F.csv 6e_lstm5 test