python .\trade_bot_lstm6_cuda.py .\data\RTY=F.csv rty_lstm6 train
python .\trade_bot_lstm6_cuda.py .\data\RTY=F.csv rty_lstm6 test

python .\trade_bot_lstm6_cuda.py .\data\CL=F.csv cl_lstm6 train
python .\trade_bot_lstm6_cuda.py .\data\CL=F.csv cl_lstm6 test

python .\trade_bot_lstm6_cuda.py .\data\LE=F.csv le_lstm6 train
python .\trade_bot_lstm6_cuda.py .\data\LE=F.csv le_lstm6 test

python .\trade_bot_lstm6_cuda.py .\data\GC=F.csv gc_lstm6 train
python .\trade_bot_lstm6_cuda.py .\data\GC=F.csv gc_lstm6 test

python .\trade_bot_lstm6_cuda.py .\data\ZN=F.csv zn_lstm6 train
python .\trade_bot_lstm6_cuda.py .\data\ZN=F.csv zn_lstm6 test

python .\trade_bot_lstm6_cuda.py .\data\6E=F.csv 6e_lstm6 train
python .\trade_bot_lstm6_cuda.py .\data\6E=F.csv 6e_lstm6 test